nginx:
  image: nginx
  labels:
    io.rancher.container.hostname_override: container_name
  environment:
   - NGINX_HOST:${virtual_host}
   - NGINX_PORT:80
   - VIRTUAL_PORT: ${public_port}
   - VIRTUAL_HOST: ${virtual_host}
   - LETSENCRYPT_HOST: ${virtual_host}  
   - LETSENCRYPT_EMAIL: ${admin_email} 
  ports:
    - "${public_port}:80"
